"""Compression checkpoint stage.

When the conversation grows past `trigger_tokens`, collapse the OLDEST turns
(everything except the most recent `keep_recent_messages`) into a single compact
summary, generated by a cheap model side-call. The summary replaces those turns.

This is the single highest-value lossy stage for long agentic sessions, because
old turns are mostly superseded scaffolding. We persist what we've already
summarised in session state so we don't re-summarise the same prefix every turn.

The side-call goes to the same upstream, reusing the caller's credentials, via
the injected `summarize_fn` (kept out of this module so it stays testable).
"""
from __future__ import annotations

from typing import Callable, List, Optional

from ..config import CheckpointConfig
from ..state import SessionState
from ..tokens import content_to_text, count_request, count_text
from .base import Stage, StageResult

# summarize_fn(text, target_tokens, model) -> summary string
SummarizeFn = Callable[[str, int, str], str]


def _local_extractive_summary(text: str, target_tokens: int) -> str:
    """Dependency-free fallback: keep the first and last slices of each turn.

    Crude but deterministic, used when no summarizer side-call is available
    (e.g. in tests). Production path uses the model side-call.
    """
    paras = [p.strip() for p in text.split("\n\n") if p.strip()]
    if not paras:
        return text[: target_tokens * 4]
    head = paras[: max(1, len(paras) // 3)]
    out, used = [], 0
    for p in head:
        t = count_text(p)
        if used + t > target_tokens:
            break
        out.append(p)
        used += t
    return "\n\n".join(out)


class CheckpointStage(Stage):
    name = "checkpoint_compression"

    def __init__(self, cfg: CheckpointConfig, summarize_fn: Optional[SummarizeFn] = None):
        self.cfg = cfg
        self.summarize_fn = summarize_fn

    def enabled(self) -> bool:
        return self.cfg.enabled

    def apply(self, request: dict, state: SessionState) -> StageResult:
        before = count_request(request)
        msgs = request.get("messages", [])
        if before < self.cfg.trigger_tokens:
            return StageResult(self.name, before, before, note="under trigger")

        keep = self.cfg.keep_recent_messages
        if len(msgs) <= keep + 1:
            return StageResult(self.name, before, before, note="too few messages")

        # the slice we will compress: everything except the recent tail
        old = list(msgs[:-keep]) if keep > 0 else list(msgs)
        recent = list(msgs[-keep:]) if keep > 0 else []

        # The checkpoint is injected as a single 'user' message, so the kept tail
        # must begin with an 'assistant' message to preserve user/assistant
        # alternation. Move leading messages from `recent` into `old` until that
        # holds (they get summarised instead of kept verbatim).
        while recent and recent[0].get("role") != "assistant":
            old.append(recent.pop(0))

        if not old:
            return StageResult(self.name, before, before, note="nothing old to fold")

        # build the text to summarise
        joined = []
        for m in old:
            role = m.get("role", "?")
            joined.append(f"[{role}]\n{content_to_text(m.get('content', ''))}")
        blob = "\n\n".join(joined)

        target = self.cfg.summary_target_tokens
        if self.summarize_fn is not None:
            try:
                summary = self.summarize_fn(blob, target, self.cfg.summarizer_model)
            except Exception as e:  # never let summarisation break the request
                summary = _local_extractive_summary(blob, target)
                note_src = f"fallback (side-call failed: {type(e).__name__})"
            else:
                note_src = "model side-call"
        else:
            summary = _local_extractive_summary(blob, target)
            note_src = "local extractive"

        checkpoint_msg = {
            "role": "user",
            "content": [
                {
                    "type": "text",
                    "text": (
                        "=== CONVERSATION CHECKPOINT (older turns compressed) ===\n"
                        + summary
                        + "\n=== END CHECKPOINT — continue from the latest messages ==="
                    ),
                }
            ],
        }

        request["messages"] = [checkpoint_msg] + recent
        state.checkpoint_text = summary
        state.checkpoint_covers = len(old)

        after = count_request(request)
        return StageResult(
            self.name,
            before,
            after,
            note=f"folded {len(old)} msgs via {note_src}",
            detail={"folded_messages": len(old), "summary_tokens": count_text(summary)},
        )
