"""Compression checkpoint stage.

When the conversation grows past `trigger_tokens`, collapse the OLDEST turns
(everything except the most recent `keep_recent_messages`) into a single compact
summary, generated by a cheap model side-call. The summary replaces those turns.

This is the single highest-value lossy stage for long agentic sessions, because
old turns are mostly superseded scaffolding. We persist what we've already
summarised in session state so we don't re-summarise the same prefix every turn.

The side-call goes to the same upstream, reusing the caller's credentials, via
the injected `summarize_fn` (kept out of this module so it stays testable).
"""
from __future__ import annotations

import hashlib
from typing import Callable, Optional

from ..config import CheckpointConfig
from ..state import SessionState
from ..tokens import content_to_text, count_request, count_text
from .base import Stage, StageResult

# summarize_fn(text, target_tokens, model, *, tool_heavy=False) -> summary string
SummarizeFn = Callable[..., str]


def _is_tool_heavy(msgs: list) -> bool:
    """Return True if this message slice is dominated by tool_result blocks.

    A session is 'tool-heavy' when more than 30% of its messages contain
    tool_result content — typical of real Claude Code sessions where the
    model reads files, runs bash commands, and searches the codebase.
    """
    if not msgs:
        return False
    tool_count = 0
    for m in msgs:
        content = m.get("content", [])
        if isinstance(content, list):
            if any(
                isinstance(b, dict) and b.get("type") == "tool_result"
                for b in content
            ):
                tool_count += 1
        elif isinstance(content, str) and "[tool_result]" in content:
            tool_count += 1
    return (tool_count / len(msgs)) > 0.30


def _local_extractive_summary(text: str, target_tokens: int) -> str:
    """Dependency-free fallback: keep head context + tail (recent decisions).

    Head gives setup/goal context; tail gives the most recent state of work.
    Crude but deterministic, used when no summarizer side-call is available
    (e.g. in tests). Production path uses the model side-call.
    """
    paras = [p.strip() for p in text.split("\n\n") if p.strip()]
    if not paras:
        return text[: target_tokens * 4]
    n_head = max(1, len(paras) // 4)
    n_tail = max(1, len(paras) // 2)
    head = paras[:n_head]
    tail_start = max(n_head, len(paras) - n_tail)
    tail = paras[tail_start:]
    selected = head + tail
    out, used = [], 0
    for p in selected:
        t = count_text(p)
        if used + t > target_tokens:
            break
        out.append(p)
        used += t
    return "\n\n".join(out)


class CheckpointStage(Stage):
    name = "checkpoint_compression"

    def __init__(self, cfg: CheckpointConfig, summarize_fn: Optional[SummarizeFn] = None):
        self.cfg = cfg
        self.summarize_fn = summarize_fn

    def enabled(self) -> bool:
        return self.cfg.enabled

    def apply(self, request: dict, state: SessionState) -> StageResult:
        before = count_request(request)
        msgs = request.get("messages", [])
        if before < self.cfg.trigger_tokens:
            return StageResult(self.name, before, before, note="under trigger")

        keep = self.cfg.keep_recent_messages
        # the slice we will compress: everything except the recent tail
        old = list(msgs[:-keep]) if keep > 0 else list(msgs)
        recent = list(msgs[-keep:]) if keep > 0 else []

        # The checkpoint is injected as a single 'user' message, so the kept tail
        # must begin with an 'assistant' message to preserve user/assistant
        # alternation. Move leading messages from `recent` into `old` until that
        # holds (they get summarised instead of kept verbatim).
        while recent and recent[0].get("role") != "assistant":
            old.append(recent.pop(0))

        if not old:
            return StageResult(self.name, before, before, note="nothing old to fold")

        # build the text to summarise
        joined = []
        for m in old:
            role = m.get("role", "?")
            joined.append(f"[{role}]\n{content_to_text(m.get('content', ''))}")
        blob = "\n\n".join(joined)
        old_tokens = count_text(blob)

        # ROI gate: don't pay for a side-call if the old bucket is already small
        # enough that summarising it would save little or nothing.
        threshold = self.cfg.summary_target_tokens * self.cfg.min_compression_ratio
        if old_tokens < threshold:
            return StageResult(
                self.name, before, before,
                note=f"old bucket too small ({old_tokens} tok < {threshold:.0f} threshold)",
            )

        # Skip the expensive side-call if this exact prefix was already summarised.
        # The client sends the full uncompressed history every turn, so without this
        # guard we'd pay for a Haiku call on every turn once the conversation is long.
        blob_hash = hashlib.sha1(blob.encode()).hexdigest()[:16]
        if state.checkpoint_hash == blob_hash and state.checkpoint_text:
            summary = state.checkpoint_text
            note_src = "cached (unchanged prefix)"
        else:
            target = self.cfg.summary_target_tokens
            tool_heavy = _is_tool_heavy(old)
            if self.summarize_fn is not None:
                try:
                    summary = self.summarize_fn(
                        blob, target, self.cfg.summarizer_model, tool_heavy=tool_heavy
                    )
                    note_src = "model side-call" + (" (tool-aware)" if tool_heavy else "")
                except Exception as e:  # never let summarisation break the request
                    summary = _local_extractive_summary(blob, target)
                    note_src = f"fallback (side-call failed: {type(e).__name__})"
            else:
                summary = _local_extractive_summary(blob, target)
                note_src = "local extractive"
            state.checkpoint_hash = blob_hash

        checkpoint_msg = {
            "role": "user",
            "content": [
                {
                    "type": "text",
                    "text": (
                        "=== CONVERSATION CHECKPOINT (older turns compressed) ===\n"
                        + summary
                        + "\n=== END CHECKPOINT — continue from the latest messages ==="
                    ),
                }
            ],
        }

        request["messages"] = [checkpoint_msg] + recent
        state.checkpoint_text = summary
        state.checkpoint_covers = len(old)

        after = count_request(request)
        return StageResult(
            self.name,
            before,
            after,
            note=f"folded {len(old)} msgs via {note_src}",
            detail={"folded_messages": len(old), "summary_tokens": count_text(summary)},
        )
